name: AmzonLinux2 1.0

on:
  push:
    paths:
    - al2/1.0/*/*/*
    - .github/workflows/amazonlinux-1.0.yml
  pull_request:
    paths:
    - al2/1.0/*/*/*
    - .github/workflows/amazonlinux-1.0.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
        - "7.2"
        - "7.3"
        node:
        - "10"
        - "12"
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build "al2/1.0/php${{ matrix.php }}/node${{ matrix.node }}"
