name: standard-1.0

on:
  push:
    paths:
      - ubuntu/1.0/*/*/*
      - .github/workflows/standard-1.0.yml
    branches:
      - main
  pull_request:
    paths:
      - ubuntu/1.0/*/*/*
      - .github/workflows/standard-1.0.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          ./.github/build.sh ubuntu standard 1.0
        env:
          USERNAME: ${{ secrets.username }}
          PASSWORD: ${{ secrets.password }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
