name: Update

on: [pull_request]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Checking Update
      uses: "docker://perl:5.30"
      with:
        args: bash -c "cpanm JSON && ./update.sh"
    - name: Commit
      env:
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        branch=update-$(date +"%Y-%m-%d-%H-%M-%S")
        git config --global user.name "Ichinose Shogo"
        git config --global user.email shogo82148@gmail.com
        git switch -c $branch
        git add .
        git commit -m "Update $(date +"%Y-%m-%d %H:%M:%S")" || exit 0
        header=$(echo -n "shogo82148:${GITHUB_TOKEN}" | base64)
        git -c http.extraheader="AUTHORIZATION: token $GITHUB_TOKEN" push -u origin $branch
        curl -H "Authorization: token $GITHUB_TOKEN" \
          -d "$(jq --arg branch $branch -n '{ "title": "Amazing new feature", "base": "master", "head": $branch }')" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls"
