name: Update

on: [push, pull_request]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Checking Update
      uses: "docker://perl:5.30"
      with:
        args: bash -c "cpanm JSON && ./update.sh"
    - name: Commit
      env:
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e
        git config --global user.name "Ichinose Shogo"
        git config --global user.email shogo82148@gmail.com
        git checkout -b hogehoge-test
        git add .
        git commit --allow-empty -m 'foobar'
        header=$(echo -n "shogo82148:${GITHUB_TOKEN}" | base64)
        git -c http.extraheader="AUTHORIZATION: basic $header" push -u origin hogehoge-test
